---
- hosts: proxmox
  become: yes
  become_user: root
  gather_facts: false
  tasks:

  - name: Create a temporary directory if it does not exist
    ansible.builtin.file:
      path: ~/temp/pihole/
      state: directory
      mode: '0777'

  - name: Checkout the git Pihole repo
    ansible.builtin.git:
      repo: 'https://github.com/gregoryca/pihole.dns.git'
      dest: ~/temp/pihole/

  - name: Create the srv directory if it does not exist
    ansible.builtin.file:
      path: ~/srv/
      state: directory
      mode: '0777'

  - name: copy git repo to remote server
    copy:
      src: ~/temp/pihole
      dest: ~/srv/
      remote_src: yes

  - name: Create docker network web-secure
    docker_network:
      name: web-secure

  - name: create and start docker compose services
    community.docker.docker_compose_v2:
      project_src: ~/srv/pihole

  - name: Delete content & directory
    file:
      state: absent
      path: ~/temp/

  - debug:
      var: ansible_facts["cmdline"]
