---
- hosts: proxmox
  become: false
  become_user: gregory
  gather_facts: True
  tasks:

    - name: stop and remove docker compose services
      community.docker.docker_compose_v2:
        project_src: ~/srv/pihole
        state: absent

    - name: Remove image pihole image
      docker_image:
        name: pihole/pihole:latest
        state: absent

    - name: pull latest version
      docker_image:
        name: pihole/pihole
        source: pull

    - name: create and start docker compose services
      community.docker.docker_compose_v2:
        project_src: ~/srv/pihole
