########################################################
# This is a basic workflow to Deploy a Nextcloud stack #
########################################################
name: Upgrade Pihole (test)

on:
  push:
    branches: [ "dev, development" ]
  pull_request:
    branches: [ "master" ]

  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Run playbook
        uses: actions/checkout@v3

      #####################################################################
      # Deploys an ansible script to manage the traefik stack deployment #
      #####################################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Deploy Ansible script for Upgrade Pihole with test inventory in secrets
        with:
          ###############################
          # Required, playbook filepath #
          ###############################
          playbook: upgrade.yml
          ############################################
          # Optional, directory where playbooks live #
          ############################################
          directory: ./deployments
          ###################
          # SSH private key #
          ###################
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ###########################
          # inventory file contents #
          ###########################
          inventory: ${{ secrets.INVENTORY }}
